on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  k6-performance-testing:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
            node-version: 16
    
      - name: Install dependencies and Build
        run: |
            yarn
            yarn build

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: webpack/check.test.js