on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  QA_SERVER: ${{ secrets.QA_SERVER }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  TOKEN_URL: ${{ secrets.TOKEN_URL }}
  SCOPE: ${{ secrets.SCOPE }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  
jobs:
  k6-performance-testing:
    name: K6 Performance Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
            node-version: 16
    
      - name: Install dependencies and Build
        run: |
            yarn
            yarn build
            echo $K6_CLOUD_TOKEN
            echo $QA_SERVER

      - name: Run local k6 test
        uses: k6io/action@v0.1
        with:
          filename: webpack/performance.test.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_TOKEN }}