on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  QA_SERVER: ${{ secrets.QA_SERVER }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  TOKEN_URL: ${{ secrets.TOKEN_URL }}
  SCOPE: ${{ secrets.SCOPE }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}

jobs:
  k6-performance-testing:
    name: K6 Performance Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: 💿 Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
            node-version: 16
    
      - name: 📈 Installing k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
          echo "---- k6 installation done ----" 
          ./k6

      - name: 🧬 Install dependencies and Build
        run: |
            yarn
            yarn build
      # this script will run webpack and create the test.js to be executed by k6

      #** TESTS with Grafana output **
      - name: 📊🧪 Running Performance Test with k6 (GRAFANA)
        run: |
          ./k6 run --out cloud webpack/performance.test.js
      # this script will run the test.js created by webpack and send the results to Grafana

      #** TESTS with local output **
      # - name: 📊🧪 Running Performance Test with k6 (LOCALLY)
      #   uses: grafana/k6-action@v0.3.1
      #   with:
      #     filename: webpack/performance.test.js